### ISSUE TITLE
TypeError: chalk[color] is not a function

### ISSUE THREAD

**Issue by zhangda89** [koajs/logger#41]
`
TypeError: chalk[color] is not a function
at log (/Users/durban/nodejs/qeeniao-wap-web/node_modules/koa-logger/index.js:119:25)
at done (/Users/durban/nodejs/qeeniao-wap-web/node_modules/koa-logger/index.js:76:9)
at ServerResponse.g (events.js:260:16)
at emitNone (events.js:72:20)
at ServerResponse.emit (events.js:166:7)
at finish (_http_outgoing.js:545:10)
at doNTCallback0 (node.js:430:9)
at process._tickDomainCallback (node.js:400:13)
`

**Comment by HardlyMirage** [comment]
I've started getting this error for no particular reason:

 ```
 TypeError: chalk[color] is not a function
      at log (/Work/streamsavers/api/node_modules/koa-logger/index.js:118:25)
      at Object.logger (/Work/streamsavers/api/node_modules/koa-logger/index.js:52:7)
      at throw (native)
      at onRejected (/Work/streamsavers/api/node_modules/co/index.js:81:24)

```

Version 1.3.0

**Comment by HardlyMirage** [comment]
This appears to happen when my `err` is a `Promise`

**Comment by murac** [comment]
So this last commit did not seem to fix the problem. I'm adding custom status codes and the bitwise operation on line 95 still returns the number divided by 100. I'm going to submit a simple PR which fixes this. And add "Magenta" for the famed "RFC 7xx: Developer Error Status Codes"

**Comment by coderhaoxin** [comment]
https://github.com/koajs/logger/pull/61#pullrequestreview-47319604
