### ISSUE TITLE
Koa-logger@2 not working if used with node < v7.6

### ISSUE THREAD

**Issue by sakivks** [koajs/logger#63]
Node version **6.9.1**

**Used** 
```
require('babel-register');
require('./src/server');
```
to transpile the code to use await async.

*server.js*
```
var Koa = require("koa");
const logger = require('koa-logger');
var app = new Koa();
var PORT = 4500;

app.use(logger());

app.use((ctx, next) => {
  ctx.body = 'gg wp'
});


app.listen(PORT);
console.log(`server listening on port ${PORT}`);
```

**Error got**  
```
C:\Work\codebase\abc\node_modules\koa-logger\index.js:36
  return async function logger (ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Work\codebase\abc\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Work\codebase\real-time-monitoring\src\server.js:2:16)
```

It started working after changing my code to 
```
require('babel-register')
({
  only: "/node_modules/koa-logger/*"
});
require('./src/server');
```

**Comment by coderhaoxin** [comment]
Yes. `koa-logger@2` needs `node@7.6+` :)

https://github.com/koajs/logger/blob/master/package.json#L41-L43

**Comment by Siyfion** [comment]
@coderhaoxin I've just stumbled across this error too, having tried deploying a `koa` app to AWS Lambda. While I know that Koa v2 was all about supporting async/await, as far as I know, this is the only module that actually _requires_ `node@7.6+`, making it almost impossible to use on Lambda.

At the moment I'm using Parcel with Babel to transpile my ES6+ code, which works fine with everything apart from this.
